name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --file-under=3 $(git ls-files '*.py')
    - name: Check code coverage
      run: |
        coverage run -m unittest discover
        coverage report -m
        coverage xml
    - name: Launch Locust
      run: |
        locust -f ./tests/locustfile.py --headless --host=http://localhost:5000 --users=10 --spawn-rate=1 --run-time=1m --csv=locust
