name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=2 $(git ls-files '*.py')
    - name: Check code coverage
      run: |
        coverage run -m unittest discover
        coverage report -m
        coverage xml
    - name: Launch App
      run: |
        cd application
        uvicorn main:app &
    - name: Install Selenium 
      run: |
        pip install selenium
    - name: Launch main2.py
      run: |
        python main2.py


  

